[package]
name = "luther"
version = "0.1.0"
authors = ["Fisher Darling <fdarling@mines.edu>"]
edition = "2018"

[[bin]]
name = "LUTHER"
path = "./src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
